image: perlchild/buildredis
env:
  - GOPATH=/var/cache/drone
script:
  - make
  - make test
deploy:
    bash:
        command: /bin/ls
notify:
  email:
    recipients:
      - eric.robibaro@radialpoint.com
