image: perlchild/buildredis
env:
  - GOPATH=/var/cache/drone
script:
  - make
  - make test
  - set|cat
deploy:
    bash:
        command: /bin/ls
publish:
  s3:
    cl: public-read
    region: us-west-1
    bucket: com.radialpoint.sa.drone-build-tool
    access_key: AKIAIAR3M6AU4RHAJJ4A
    secret_key: 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
    source: src/redis-server
    target: latest/
notify:
  email:
    recipients:
      - perlchild@robibaro.org
