image: perlchild/buildredis
env:
  - GOPATH=/var/cache/drone
script:
  - make
  - make test
  - set|cat
deploy:
    bash:
        command: /bin/ls
publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: com.radialpoint.sa.drone-build-tool
    access_key: $AWS_KEY
    secret_key: $AWS_SECRET
    source: deb/drone.deb
    target: latest/
notify:
  email:
    recipients:
      - perlchild@robibaro.org
