image: perlchild/buildredis
env:
  - GOPATH=/var/cache/drone
script:
  - make
  - make test
services:
  - redis
publish:
    swift:
        username: eric.robibaro@radialpoint.com
        password: EsJad007()
        auth_url: https://storage.bhs-1.runabove.io/v1/AUTH_f91c05d4f310499fae2b40c51ef59721
        region: BHS
        container: crabbucket
        source: /var/cache/drone/redis
        target: latest/redis
notify:
  email:
    recipients:
      - eric.robibaro@radialpoint.com
